---
- name: Install package {{ mypkg }}without dependencies of OS
  hosts: "{{ myhost }}"
  tasks:
    - name: Install "{{ mypkg }}"
      package:
        name: "{{ mypkg }}"
        state: "{{ mystate }}"
      check_mode: "{{ mymode }}"
