---

- name: Create user and set in SUDO file 
  hosts: "{{ myhost }}"
  tasks:
    - name: Create {{ user_name }} on mn-node2
      user:
        name: "{{ user_name }}"
        state: "{{ mystate }}"
        password: "{{ pass_word | password_hash('sha512') }}"

    - name: Update sudoers file
      lineinfile:
        path: /etc/sudoers
        state: "{{ mystate }}"
        line: "{{ user_name }} ALL=(ALL) NOPASSWD: ALL"
        validate: /usr/sbin/visudo -cf %s

